<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="W1651474" ignored="0" name="Test2" tests="1" failures="1" timestamp="2021-05-08T17:18:07 IST" time="163.41" errors="0">
  <testcase name="validationOfTitle" time="154.676" classname="SelCourse.E2EProject.validateTitle">
    <failure type="java.lang.AssertionError" message="expected [Featured Couses] but found [Featured Courses]">
      <![CDATA[java.lang.AssertionError: expected [Featured Couses] but found [Featured Courses]
at SelCourse.E2EProject.validateTitle.validationOfTitle(validateTitle.java:27)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validationOfTitle -->
</testsuite> <!-- Test2 -->
